builds:
  - goarch: [amd64]
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
