name: release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: actions/checkout@v2

      - name: git history
        run: git fetch --prune --unshallow

      - uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.126.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
